# Generated by Django 2.0.5 on 2018-05-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_ap', '0008_auto_20180507_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premierleaguematch',
            old_name='date',
            new_name='match_date',
        ),
    ]
