# Generated by Django 2.0.5 on 2018-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_ap', '0009_auto_20180507_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierleaguematch',
            name='match_date',
            field=models.DateField(max_length=12),
        ),
    ]
