# Generated by Django 2.0.5 on 2018-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_ap', '0010_auto_20180507_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(max_length=12)),
                ('group', models.CharField(max_length=25)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('result', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
