# Generated by Django 2.0.5 on 2018-05-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_ap', '0012_auto_20180508_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldcupmatch',
            name='match_date',
            field=models.DateTimeField(max_length=12),
        ),
    ]
