# Generated by Django 2.0.5 on 2018-05-09 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_ap', '0014_auto_20180509_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupmatch',
            name='match_time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
